---

# Certkit Sync Ansible Role
#   This role installs and configures a synchronization script which downloads and updates Certkit SSL certificates when new ones are issued by certkit.io.
#
# How to Use This Role
#   This role expects vars containing all the information necessary to pull your certificate from Certkit storage.
#
# Required Variables
#   certkit_bucket - The name of your certkit storage bucket. Get this from the Certkit UI.
#   certkit_access_key - The access key for your certkit storage bucket. Get this from the Certkit UI.
#   certkit_secret_key - The secret key for your certkit storage bucket. Get this from the Certkit UI.
#   certkit_common_name - The domain name of the certificate. Prefix with * if it's a wildcard.
#   certkit_dir - The directory where the certkit sync script and config file will be placed. Arbitrary, pick what you'd like. Should be unique if multiple certkit scripts are installed on the same box!
#   certkit_update_cmd - Certkit sync runs this command whenever the certificates are updated. Use to inform the server of a new certificate.
#   certkit_pem_destination - File path where Certkit sync will write the certificate PEM file. This is wherever your server software expects the certificate to live.
#   certkit_key_destination - File path where Certkit sync will save the certificate private key file. This is wherever your server software expects the certificate to live.
#
# Example Usage
#   - name: Configure Certkit
#     vars:
#       certkit_bucket: certkit-1234
#       certkit_access_key: YOUR_ACCESS_KEY
#       certkit_secret_key: YOUR_SECRET_KEY
#       certkit_common_name: "*.yourdomain.com"
#       certkit_dir: /opt/certkit-nginx
#       certkit_update_cmd: "/usr/sbin/nginx -s reload"  
#       certkit_pem_destination: "/etc/nginx/yourdomain.pem"
#       certkit_key_destination: "/etc/nginx/yourdomain.key"
#     include_role: name=certkit


- name: Make Certkit Directory
  file: 
    path: "{{certkit_dir}}"
    state: directory

- name: Create Certkit Config
  template:
    src: templates/certkit.conf.j2
    dest: "{{certkit_dir}}/certkit.conf"
    mode: 0600
  notify: Run Certkit Sync

- name: Copy Sync Script
  copy:
    src: files/certkit-sync.sh
    dest: "{{certkit_dir}}/certkit-sync.sh"
    mode: 0755

- name: Schedule Script In Cron
  cron:
    name: "run certkit-sync from {{certkit_dir}}"
    minute: "{{ (59 | random(seed=certkit_dir)) }}"
    hour: "*/4"
    job: "{{certkit_dir}}/certkit-sync.sh 2>&1 | logger -t certkit-sync"
